spring:
  application:
    name: AccountMe
  security:
    user:
      # a revoir
      name: user
      password: user
  elasticsearch:
    uris: http://localhost:9200
    # User et mot de passe à creer via Kibana avec les bons roles
    username: AccountMe
    password: 123456

server:
  port: 8081
  servlet:
    context-path: /account-me

# Pas utiliser, a voir si on garde ou supprime, car ce serai mieux qu'un user et password
account-me:
  elasticsearch:
    api-key: ZWNsNkFwWUI1SU1zYmkyRzdmMGE6Y05hMHFZVzJRb3VlWlctN0RoeEd6UQ==