spring:
  batch:
    job:
      enabled: true
  application:
    name: account-me-batch
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  elasticsearch:
    uris: http://localhost:9200
    username: AccountMeBatch
    password: 123456

account-me:
  directory:
    input-pattern: input/*.pdf
    output: ./output