spring:
  application:
    name: AccountMe
#    TODO Uncomment dependency in pom.xml
#  security:
#    user:
#      name: user
#      password: user
  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: test

server:
  port: 8081
  servlet:
    context-path: /account-me
logging:
  level:
    org.springframework: WARN